# Generated by Django 4.1.7 on 2023-03-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_menu', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
