# Generated by Django 4.0.5 on 2022-08-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_menu', '0006_alter_dish_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dish_category',
            name='created_by',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
