# Generated by Django 4.0.5 on 2022-09-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_menu', '0008_alter_dish_created_by_alter_dish_category_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_category',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
