# Generated by Django 4.0.5 on 2022-09-20 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_menu', '0009_alter_dish_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
