# Generated by Django 4.0.5 on 2022-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_menu', '0012_alter_dish_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='../media'),
        ),
    ]
