# Generated by Django 4.0.5 on 2023-03-25 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_menu', '0013_alter_dish_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish_Category',
            new_name='DishCategory',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='./media'),
        ),
    ]
